lan_1 = {"af": "Afrikaans",
       "sq": "Albanian",
       "am": "Amharic",
       "ar": "Arabic",
       "hy": "Armenian",
       "az": "Azerbaijani",
       "eu": "Basque",
       "be": "Belarusian",
       "bn": "Bengali",
       "bs": "Bosnian",
       "bg": "Bulgarian",
       "ca": "Catalan",
       "ceb": "Cebuano",
       "ny": "Chichewa",
       "zh-CN": "Chinese",
       "co": "Corsican",
       "hr": "Croatian",
       "cs": "Czech",
       "da": "Danish",
       "nl": "Dutch",
       "en": "English",
       "eo": "Esperanto",
       "et": "Estonian",
       "tl": "Filipino",
       "fi": "Finnish",
       "fr": "French",
       "fy": "Frisian",
       "gl": "Galician",
       "ka": "Georgian",
       "de": "German",
       "el": "Greek",
       "gu": "Gujarati",
       "ht": "Haitian Creole",
       "ha": "Hausa",
       "haw": "Hawaiian",
       "iw": "Hebrew",
       "hi": "Hindi",
       "hmn": "Hmong",
       "hu": "Hungarian",
       "is": "Icelandic",
       "ig": "Igbo",
       "id": "Indonesian",
       "ga": "Irish",
       "it": "Italian",
       "ja": "Japanese",
       "jw": "Javanese",
       "kn": "Kannada",
       "kk": "Kazakh",
       "km": "Khmer",
       "rw": "Kinyarwanda",
       "ko": "Korean",
       "ku": "Kurdish (Kurmanji)",
       "ky": "Kyrgyz",
       "lo": "Lao",
       "la": "Latin",
       "lv": "Latvian",
       "lt": "Lithuanian",
       "lb": "Luxembourgish",
       "mk": "Macedonian",
       "mg": "Malagasy",
       "ms": "Malay",
       "ml": "Malayalam",
       "mt": "Maltese",
       "mi": "Maori",
       "mr": "Marathi",
       "mn": "Mongolian",
       "my": "Myanmar (Burmese)",
       "ne": "Nepali",
       "no": "Norwegian",
       "or": "Odia (Oriya)",
       "ps": "Pashto",
       "fa": "Persian",
       "pl": "Polish",
       "pt": "Portuguese",
       "pa": "Punjabi",
       "ro": "Romanian",
       "ru": "Russian",
       "sm": "Samoan",
       "gd": "Scots Gaelic",
       "sr": "Serbian",
       "st": "Sesotho",
       "sn": "Shona",
       "sd": "Sindhi",
       "si": "Sinhala",
       "sk": "Slovak",
       "sl": "Slovenian",
       "so": "Somali",
       "es": "Spanish",
       "su": "Sundanese",
       "sw": "Swahili",
       "sv": "Swedish",
       "tg": "Tajik",
       "ta": "Tamil",
       "tt": "Tatar",
       "te": "Telugu",
       "th": "Thai",
       "tr": "Turkish",
       "tk": "Turkmen",
       "uk": "Ukrainian",
       "ur": "Urdu",
       "ug": "Uyghur",
       "uz": "Uzbek",
       "vi": "Vietnamese",
       "cy": "Welsh",
       "xh": "Xhosa",
       "yi": "Yiddish",
       "yo": "Yoruba",
       "zu": "Zulu"
       }

lan_2 = {'af': 'Afrikaans',
         'ar': 'Arabic',
         'bn': 'Bengali',
         'bs': 'Bosnian',
         'ca': 'Catalan',
         'cs': 'Czech',
         'cy': 'Welsh',
         'da': 'Danish',
         'de': 'German',
         'el': 'Greek',
         'en': 'English',
         'eo': 'Esperanto',
         'es': 'Spanish',
         'et': 'Estonian',
         'fi': 'Finnish',
         'fr': 'French',
         'gu': 'Gujarati',
         'hi': 'Hindi',
         'hr': 'Croatian',
         'hu': 'Hungarian',
         'hy': 'Armenian',
         'id': 'Indonesian',
         'is': 'Icelandic',
         'it': 'Italian',
         'ja': 'Japanese',
         'jw': 'Javanese',
         'km': 'Khmer',
         'kn': 'Kannada',
         'ko': 'Korean',
         'la': 'Latin',
         'lv': 'Latvian',
         'mk': 'Macedonian',
         'ml': 'Malayalam',
         'mr': 'Marathi',
         'my': 'Myanmar (Burmese)',
         'ne': 'Nepali',
         'nl': 'Dutch',
         'no': 'Norwegian',
         'pl': 'Polish',
         'pt': 'Portuguese',
         'ro': 'Romanian',
         'ru': 'Russian',
         'si': 'Sinhala',
         'sk': 'Slovak',
         'sq': 'Albanian',
         'sr': 'Serbian',
         'su': 'Sundanese',
         'sv': 'Swedish',
         'sw': 'Swahili',
         'ta': 'Tamil',
         'te': 'Telugu',
         'th': 'Thai',
         'tl': 'Filipino',
         'tr': 'Turkish',
         'uk': 'Ukrainian',
         'ur': 'Urdu',
         'vi': 'Vietnamese',
         'zh-cn': 'Chinese',
         'zh-tw': 'Chinese (Mandarin/Taiwan)',
         'en-us': 'English (US)',
         'en-ca': 'English (Canada)',
         'en-uk': 'English (UK)',
         'en-gb': 'English (UK)',
         'en-au': 'English (Australia)',
         'en-gh': 'English (Ghana)',
         'en-in': 'English (India)',
         'en-ie': 'English (Ireland)',
         'en-nz': 'English (New Zealand)',
         'en-ng': 'English (Nigeria)',
         'en-ph': 'English (Philippines)',
         'en-za': 'English (South Africa)',
         'en-tz': 'English (Tanzania)',
         'fr-ca': 'French (Canada)',
         'fr-fr': 'French (France)',
         'pt-br': 'Portuguese (Brazil)',
         'pt-pt': 'Portuguese (Portugal)',
         'es-es': 'Spanish (Spain)',
         'es-us': 'Spanish (United States)'}

lan_3 = {'af': 'afrikaans',
         'sq': 'albanian',
         'am': 'amharic',
         'ar': 'arabic',
         'hy': 'armenian',
         'az': 'azerbaijani',
         'eu': 'basque',
         'be': 'belarusian',
         'bn': 'bengali',
         'bs': 'bosnian',
         'bg': 'bulgarian',
         'ca': 'catalan',
         'ceb': 'cebuano',
         'ny': 'chichewa',
         'zh-cn': 'chinese',
         'zh-tw': 'chinese (traditional)', 'co': 'corsican', 'hr': 'croatian', 'cs': 'czech', 'da': 'danish', 'nl': 'dutch', 'en': 'english', 'eo': 'esperanto', 'et': 'estonian', 'tl': 'filipino', 'fi': 'finnish', 'fr': 'french', 'fy': 'frisian', 'gl': 'galician', 'ka': 'georgian', 'de': 'german', 'el': 'greek', 'gu': 'gujarati', 'ht': 'haitian creole', 'ha': 'hausa', 'haw': 'hawaiian', 'iw': 'hebrew', 'he': 'hebrew', 'hi': 'hindi', 'hmn': 'hmong', 'hu': 'hungarian', 'is': 'icelandic', 'ig': 'igbo', 'id': 'indonesian', 'ga': 'irish', 'it': 'italian', 'ja': 'japanese', 'jw': 'javanese', 'kn': 'kannada', 'kk': 'kazakh', 'km': 'khmer', 'ko': 'korean', 'ku': 'kurdish (kurmanji)', 'ky': 'kyrgyz', 'lo': 'lao', 'la': 'latin', 'lv': 'latvian', 'lt': 'lithuanian', 'lb': 'luxembourgish', 'mk': 'macedonian', 'mg': 'malagasy', 'ms': 'malay', 'ml': 'malayalam', 'mt': 'maltese', 'mi': 'maori', 'mr': 'marathi', 'mn': 'mongolian', 'my': 'myanmar (burmese)', 'ne': 'nepali', 'no': 'norwegian', 'or': 'odia', 'ps': 'pashto', 'fa': 'persian', 'pl': 'polish', 'pt': 'portuguese', 'pa': 'punjabi', 'ro': 'romanian', 'ru': 'russian', 'sm': 'samoan', 'gd': 'scots gaelic', 'sr': 'serbian', 'st': 'sesotho', 'sn': 'shona', 'sd': 'sindhi', 'si': 'sinhala', 'sk': 'slovak', 'sl': 'slovenian', 'so': 'somali', 'es': 'spanish', 'su': 'sundanese', 'sw': 'swahili', 'sv': 'swedish', 'tg': 'tajik', 'ta': 'tamil', 'te': 'telugu', 'th': 'thai', 'tr': 'turkish', 'uk': 'ukrainian', 'ur': 'urdu', 'ug': 'uyghur', 'uz': 'uzbek', 'vi': 'vietnamese', 'cy': 'welsh', 'xh': 'xhosa', 'yi': 'yiddish', 'yo': 'yoruba', 'zu': 'zulu'}

